version: '3.9'
services:
    app:
        image: dockerize:latest
        build:
            target: app
            context: .
            args:
                - APP_ENV=${APP_ENV}
        ports:
            -   '8000:80'
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            -   database
        volumes:
            -  .:/var/www/html

    database:
        image: mysql:latest
        ports:
            -   '3303:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
